name: CD

on:
  push:
    branches:
      - master

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'temurin'
      - name: Install Maven
        run: sudo apt-get install -y maven
      - name: Build
        run: mvn clean install
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Azure CLI script file
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            mvn azure-webapp:deploy
