name: CD

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'temurin'
      - name: Build
        run: mvn clean install
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Azure CLI script file
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az webapp deploy --resource-group "ResourceMoverRG-eastus2-eastus-eus2" --name "springBootAngularApp" --src-path bike-0.0.1-SNAPSHOT.jar --type jar --async true
