name: Java CI with Maven

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Set up JDK 1.8
      uses: actions/setup-java@v3
      with:
        java-version: '8.0.342+7'
        distribution: 'temurin'
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      working-directory: ${{ github.workspace }}

    - name: Upload JAR Artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-jar
        path: target/*.jar
          
    - name: Azure WebApp
      uses: Azure/webapps-deploy@v3
      with:
        app-name: Spring-boot-angular-app
        package: ${{ github.workspace }}/target/bike-0.0.1-SNAPSHOT.jar

    # Azure logout 
    - name: logout
      run: |
        az logout
